name: CI
on:
  push:
    branches: [release]
  pull_request:
    types: [opened, synchronized]
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build
          touch ./_site/.nojekyll
          rm -f ./_site/feed.xml

      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/release' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: _site
